[window]
decorations = "None"
dimensions = { columns = 160, lines = 37 }
opacity = 0.95
padding = { x = 5, y = 5 }
dynamic_padding = true

[scrolling]
multiplier = 3

[font]
normal = { family = "JetBrains Mono", style = "Light 300" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "BoldItalic" }
size = 13
