[window]
decorations = "None"
dimensions = { columns = 155, lines = 33 }
opacity = 0.95
padding = { x = 10, y = 10 }
dynamic_padding = true

[scrolling]
multiplier = 3

[font]
normal = { family = "JetBrains Mono", style = "Light 300" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "BoldItalic" }
size = 13

[cursor]
style = { shape = "Beam", blinking = "Never" }

